---
include:
- "**/*.rb"
exclude:
- "*/spec/**/*"
- "*test/**/*"
- "*/vendor/**/*"
- vendor/**/*
- ".bundle/**/*"
- sample/**/*
- guides/**/*
- sandbox/**/*
- pkg/**/*
require: []
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
max_files: 50_000
